# Generated by Django 5.0.4 on 2024-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_like_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
